import type { AppLocale } from '@/i18n/routing'

export const PROGRAMME_DAYS = ['2027-05-20', '2027-05-21', '2027-05-22', '2027-05-23'] as const

export type ProgrammeType = 'workshop' | 'party' | 'show' | 'other'
export type ProgrammeLevel = 'all' | 'beginner' | 'intermediate' | 'advanced'

export type PublishedSlot = {
  id: string
  date: (typeof PROGRAMME_DAYS)[number]
  startTime: string
  endTime?: string
  type: ProgrammeType
  level: ProgrammeLevel
  room: string
  artists?: string
  title: Record<AppLocale, string>
}

export const publishedProgramme: PublishedSlot[] = [
  {
    id: 'thu-checkin',
    date: '2027-05-20',
    startTime: '16:00',
    endTime: '18:00',
    type: 'other',
    level: 'all',
    room: 'Lobby',
    title: { fr: 'Accueil et badges', en: 'Check-in and badges', es: 'Acreditación' },
  },
  {
    id: 'thu-welcome',
    date: '2027-05-20',
    startTime: '18:00',
    endTime: '19:00',
    type: 'other',
    level: 'all',
    room: 'Hall',
    title: { fr: 'Ouverture et welcome', en: 'Opening welcome', es: 'Bienvenida' },
  },
  {
    id: 'thu-show',
    date: '2027-05-20',
    startTime: '20:30',
    endTime: '21:15',
    type: 'show',
    level: 'all',
    room: 'Main room',
    artists: 'Kevin y Lucia',
    title: { fr: "Show d'ouverture", en: 'Opening show', es: 'Show de apertura' },
  },
  {
    id: 'thu-party',
    date: '2027-05-20',
    startTime: '21:30',
    endTime: '03:00',
    type: 'party',
    level: 'all',
    room: 'Main room',
    artists: 'DJ Alma',
    title: { fr: "Soirée d'ouverture", en: 'Opening night social', es: 'Fiesta de apertura' },
  },
  {
    id: 'fri-musicality',
    date: '2027-05-21',
    startTime: '11:00',
    endTime: '12:30',
    type: 'workshop',
    level: 'advanced',
    room: 'Atlas',
    artists: 'Kira Santos, Marco Duarte',
    title: { fr: 'Musicalité avancée', en: 'Advanced musicality', es: 'Musicalidad avanzada' },
  },
  {
    id: 'fri-body',
    date: '2027-05-21',
    startTime: '12:45',
    endTime: '14:15',
    type: 'workshop',
    level: 'intermediate',
    room: 'Palmier',
    artists: 'Jordi & Judith',
    title: { fr: 'Body movement', en: 'Body movement', es: 'Body movement' },
  },
  {
    id: 'fri-sensual',
    date: '2027-05-21',
    startTime: '15:00',
    endTime: '16:30',
    type: 'workshop',
    level: 'all',
    room: 'Atlas',
    artists: 'Kevin y Lucia',
    title: { fr: 'Sensual styling', en: 'Sensual styling', es: 'Sensual styling' },
  },
  {
    id: 'fri-daysocial',
    date: '2027-05-21',
    startTime: '17:00',
    endTime: '19:00',
    type: 'party',
    level: 'all',
    room: 'Jardin',
    title: { fr: 'Day social', en: 'Day social', es: 'Social de día' },
  },
  {
    id: 'fri-show',
    date: '2027-05-21',
    startTime: '21:00',
    endTime: '21:40',
    type: 'show',
    level: 'all',
    room: 'Main room',
    artists: 'Jordi & Judith',
    title: { fr: 'Show du vendredi', en: 'Friday show', es: 'Show del viernes' },
  },
  {
    id: 'fri-party',
    date: '2027-05-21',
    startTime: '22:00',
    endTime: '04:00',
    type: 'party',
    level: 'all',
    room: 'Main room',
    artists: 'DJ Alma',
    title: { fr: 'Soirée du vendredi', en: 'Friday night social', es: 'Fiesta del viernes' },
  },
  {
    id: 'sat-footwork',
    date: '2027-05-22',
    startTime: '11:00',
    endTime: '12:30',
    type: 'workshop',
    level: 'advanced',
    room: 'Atlas',
    artists: 'Marco Duarte',
    title: { fr: 'Footwork', en: 'Footwork', es: 'Footwork' },
  },
  {
    id: 'sat-musicality',
    date: '2027-05-22',
    startTime: '11:00',
    endTime: '12:30',
    type: 'workshop',
    level: 'intermediate',
    room: 'Palmier',
    artists: 'Kevin y Lucia',
    title: { fr: 'Musicalité et pauses', en: 'Musicality and pauses', es: 'Musicalidad y pausas' },
  },
  {
    id: 'sat-lady',
    date: '2027-05-22',
    startTime: '13:00',
    endTime: '14:30',
    type: 'workshop',
    level: 'all',
    room: 'Atlas',
    artists: 'Kira Santos',
    title: { fr: 'Lady styling', en: 'Lady styling', es: 'Lady styling' },
  },
  {
    id: 'sat-connection',
    date: '2027-05-22',
    startTime: '13:00',
    endTime: '14:30',
    type: 'workshop',
    level: 'intermediate',
    room: 'Palmier',
    artists: 'Jordi & Judith',
    title: { fr: 'Connexion et frame', en: 'Connection and frame', es: 'Conexión y frame' },
  },
  {
    id: 'sat-master',
    date: '2027-05-22',
    startTime: '15:00',
    endTime: '16:30',
    type: 'workshop',
    level: 'advanced',
    room: 'Atlas',
    artists: 'Kevin y Lucia',
    title: { fr: 'Masterclass samedi', en: 'Saturday masterclass', es: 'Masterclass del sábado' },
  },
  {
    id: 'sat-daysocial',
    date: '2027-05-22',
    startTime: '17:00',
    endTime: '19:30',
    type: 'party',
    level: 'all',
    room: 'Jardin',
    title: { fr: 'Day social', en: 'Day social', es: 'Social de día' },
  },
  {
    id: 'sat-gala',
    date: '2027-05-22',
    startTime: '21:00',
    endTime: '22:00',
    type: 'show',
    level: 'all',
    room: 'Main room',
    artists: 'Kevin y Lucia, Jordi & Judith',
    title: { fr: 'Gala show', en: 'Gala show', es: 'Gala show' },
  },
  {
    id: 'sat-party',
    date: '2027-05-22',
    startTime: '22:15',
    endTime: '04:00',
    type: 'party',
    level: 'all',
    room: 'Main room',
    artists: 'DJ Alma',
    title: { fr: 'Soirée samedi', en: 'Saturday night social', es: 'Fiesta del sábado' },
  },
  {
    id: 'sun-foundations',
    date: '2027-05-23',
    startTime: '11:00',
    endTime: '12:30',
    type: 'workshop',
    level: 'beginner',
    room: 'Palmier',
    artists: 'Kira Santos',
    title: { fr: 'Bachata foundations', en: 'Bachata foundations', es: 'Bases de bachata' },
  },
  {
    id: 'sun-improv',
    date: '2027-05-23',
    startTime: '11:00',
    endTime: '12:30',
    type: 'workshop',
    level: 'advanced',
    room: 'Atlas',
    artists: 'Marco Duarte',
    title: { fr: 'Improvisation', en: 'Improvisation', es: 'Improvisación' },
  },
  {
    id: 'sun-musicality',
    date: '2027-05-23',
    startTime: '13:00',
    endTime: '14:30',
    type: 'workshop',
    level: 'intermediate',
    room: 'Atlas',
    artists: 'Jordi & Judith',
    title: { fr: 'Musicalité du dimanche', en: 'Sunday musicality', es: 'Musicalidad del domingo' },
  },
  {
    id: 'sun-master',
    date: '2027-05-23',
    startTime: '13:00',
    endTime: '14:30',
    type: 'workshop',
    level: 'all',
    room: 'Palmier',
    artists: 'Kevin y Lucia',
    title: { fr: 'Masterclass de clôture', en: 'Closing masterclass', es: 'Masterclass de cierre' },
  },
  {
    id: 'sun-daysocial',
    date: '2027-05-23',
    startTime: '15:00',
    endTime: '17:00',
    type: 'party',
    level: 'all',
    room: 'Jardin',
    title: { fr: 'Day social', en: 'Day social', es: 'Social de día' },
  },
  {
    id: 'sun-show',
    date: '2027-05-23',
    startTime: '18:30',
    endTime: '19:15',
    type: 'show',
    level: 'all',
    room: 'Main room',
    artists: 'Kevin y Lucia, DJ Alma',
    title: { fr: 'Show de clôture', en: 'Closing show', es: 'Show de cierre' },
  },
  {
    id: 'sun-party',
    date: '2027-05-23',
    startTime: '19:30',
    endTime: '00:00',
    type: 'party',
    level: 'all',
    room: 'Main room',
    artists: 'DJ Alma',
    title: { fr: 'Soirée de clôture', en: 'Closing night social', es: 'Fiesta de cierre' },
  },
]

export function festivalDateKey(value?: string | null) {
  if (!value) return ''
  const parsed = new Date(value)
  if (Number.isNaN(parsed.getTime())) return value.slice(0, 10)
  return new Date(parsed.getTime() + 12 * 60 * 60 * 1000).toISOString().slice(0, 10)
}

export function slotsForDay(date: string, locale: AppLocale) {
  return publishedProgramme
    .filter((slot) => slot.date === date)
    .map((slot) => ({
      id: slot.id,
      title: slot.title[locale],
      startTime: slot.startTime,
      endTime: slot.endTime,
      type: slot.type,
      room: slot.room,
      artists: slot.artists || null,
      level: slot.level,
    }))
}
